<?xml version="1.0"?>
<!-- Basic differential drive mobile base -->
<robot name="wombat" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="base_width" value="1.0"/>
  <xacro:property name="base_length" value="0.5"/>
  <xacro:property name="base_height" value="0.01"/>

  <xacro:property name="motor_width" value="0.06"/>
  <xacro:property name="motor_length" value="0.06"/>
  <xacro:property name="motor_height" value="0.21"/>

  <xacro:property name="motor_axis_radius" value="0.01"/>
  <xacro:property name="motor_axis_width" value="0.03"/>

  <xacro:property name="arm_motor_one_radius" value="0.005"/>
  <xacro:property name="arm_motor_one_width" value="0.12"/>

  <xacro:property name="arm_motor_two_radius" value="0.005"/>
  <xacro:property name="arm_motor_two_width" value="0.15"/>

  <xacro:property name="arm_radius" value="0.005"/>
  <xacro:property name="arm_width" value="0.47"/>


  <!-- Define intertial property macros  -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="Neon-Pink">
        <color rgba="0.996078431 0.003921569 0.603921569 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <xacro:box_inertia m="15" w="${base_width}" d="${base_length}" h="${base_height}"/>
  </link>

  <link name="motor_one_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${motor_length} ${motor_width} ${motor_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${motor_length} ${motor_width} ${motor_height}"/>
      </geometry>
    </collision>

    <xacro:box_inertia m="1" w="${motor_width}" d="${motor_length}" h="${motor_height}"/>
  </link>

  <link name="motor_two_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${motor_length} ${motor_width} ${motor_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${motor_length} ${motor_width} ${motor_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="1" w="${motor_width}" d="${motor_length}" h="${motor_height}"/>
  </link>

  <!-- Robot Footprint -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
  </joint>

  <joint name="motor_one_joint" type="fixed">
    <parent link="base_link"/>
    <child link="motor_one_link"/>
    <origin xyz="-0.1 -0.4 ${base_height/2 + motor_width/2}" rpy="0 1.57 0"/>
  </joint>

  <joint name="motor_two_joint" type="fixed">
    <parent link="base_link"/>
    <child link="motor_two_link"/>
    <origin xyz="${-0.1+motor_height/2+motor_axis_width+arm_motor_one_radius/2} ${-0.13-motor_height/2-motor_axis_width} ${base_height/2 + motor_width/2}" rpy="0 1.57 1.57"/>
  </joint>

  <link name="motor_axis_one_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <cylinder radius="${motor_axis_radius}" length="${motor_axis_width}"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${motor_axis_radius}" length="${motor_axis_width}"/>
      </geometry>
    </collision>
     <xacro:cylinder_inertia m="0.5" r="${motor_axis_radius}" h="${motor_axis_width}"/>
  </link>

  <link name="motor_axis_two_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${motor_axis_radius}" length="${motor_axis_width}"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${motor_axis_radius}" length="${motor_axis_width}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.5" r="${motor_axis_radius}" h="${motor_axis_width}"/>
  </link>

  <joint name="motor_axis_one_joint" type="continuous">
    <parent link="motor_one_link"/>
    <child link="motor_axis_one_link"/>
    <origin xyz="0 0 ${motor_height/2 + motor_axis_width/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <joint name="motor_axis_two_joint" type="continuous">
    <parent link="motor_two_link"/>
    <child link="motor_axis_two_link"/>
    <origin xyz="0 0 ${motor_height/2 + motor_axis_width/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="arm_motor_one_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${arm_motor_one_radius}" length="${arm_motor_one_width}"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${arm_motor_one_radius}" length="${arm_motor_one_width}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.1" r="${arm_motor_one_radius}" h="${arm_motor_one_width}"/>
  </link>

  <joint name="arm_motor_one_joint" type="fixed">
    <parent link="motor_axis_one_link"/>
    <child link="arm_motor_one_link"/>
    <origin xyz="${-arm_motor_one_width/2} 0 ${motor_axis_width/2}" rpy="0 1.57 0"/>
  </joint>

  <link name="arm_motor_two_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${arm_motor_two_radius}" length="${arm_motor_two_width}"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${arm_motor_two_radius}" length="${arm_motor_two_width}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.1" r="${arm_motor_two_radius}" h="${arm_motor_two_width}"/>
  </link>

  <joint name="arm_motor_two_joint" type="fixed">
    <parent link="motor_axis_two_link"/>
    <child link="arm_motor_two_link"/>
    <origin xyz="${-arm_motor_two_width/2} 0 ${motor_axis_width/2}" rpy="0 1.57 0"/>
  </joint>

  <link name="arm_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_width}"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_width}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.1" r="${arm_radius}" h="${arm_width}"/>
  </link>

  <plugin name="joint_controller" filename="libjoint_controller.so"/>
    <joint name="arm_joint" type="fixed">
      <parent link="arm_motor_one_link"/>
      <child link="arm_link"/>
      <origin xyz="0 ${arm_motor_one_width/2} ${-arm_motor_one/2}" rpy="1.57 0 0"/>
    </joint>

<!--  <joint name="arm_joint" type="fixed">-->
<!--    <parent link="arm_link"/>-->
<!--    <child link="arm_motor_one_link"/>-->
<!--    <origin xyz="0 ${arm_width/2} ${-arm_width/2}" rpy="0 0 0"/>-->
<!--  </joint>-->

<!--  <gazebo>-->
<!--  <joint name="arm_2_joint" type="prismatic">-->
<!--    <parent link="arm_motor_two_link"/>-->
<!--    <child link="arm_link"/>-->
<!--    <origin xyz="0 0 ${-arm_motor_one_width/2}" rpy="0 0 0"/>-->
<!--    <axis xyz="0 0 1"/>-->
<!--    <limit effort="0.0" lower="${-arm_width/2}" upper="${arm_width/2}" velocity="0.0"/>-->
<!--  </joint>-->
<!--  </gazebo>-->
  <gazebo>

  </gazebo>

</robot>